module.exports = {
  "extends": [
    "stylelint-config-standard"
  ],
  "overrides": [
    { "files": ["**/*.css"] }
  ],
  "plugins": [
    "@stylistic/stylelint-plugin",
    "stylelint-file-max-lines"
  ],
  "rules": {
    "declaration-property-value-no-unknown": true,
    "media-feature-name-value-no-unknown": true,
    "media-feature-name-no-vendor-prefix": true,
    "media-query-no-invalid": true,
    "property-no-vendor-prefix": [true, { "ignoreProperties": ["background-clip", "text-fill-color"] }],
    "selector-no-vendor-prefix": true,
    "value-no-vendor-prefix": true,
    "length-zero-no-unit": true,
    "function-name-case": "lower",
    "selector-type-case": "lower",
    "value-keyword-case": "lower",
    "alpha-value-notation": "percentage",
    "color-function-notation": "modern",
    "number-max-precision": 3,
    "color-hex-length": "short",
    "hue-degree-notation": "angle",
    "color-no-invalid-hex": true,
    "import-notation": "url",
    "keyframe-selector-notation": "percentage-unless-within-keyword-only-block",
    "media-feature-range-notation": "context",
    "selector-pseudo-element-colon-notation": "double",
    "font-family-name-quotes": "always-where-recommended",
    "function-url-quotes": "always",
    "selector-attribute-quotes": "always",
    "shorthand-property-no-redundant-values": true,
    "comment-whitespace-inside": "always",
    "at-rule-no-vendor-prefix": true,
    "selector-type-no-unknown": [true, { "ignore": ["custom-elements"] }],
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "font-family-no-duplicate-names": true,
    "keyframe-block-no-duplicate-selectors": true,
    "no-duplicate-at-import-rules": true,
    "block-no-empty": true,
    "selector-anb-no-unmatchable": true,
    "no-unknown-animations": true,
    "property-no-unknown": true,
    "annotation-no-unknown": true,
    "at-rule-no-unknown": true,
    "media-feature-name-value-no-unknown": true,
    "function-no-unknown": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "comment-no-empty": true,
    "font-family-no-missing-generic-family-keyword": true,
    "named-grid-areas-no-invalid": true,
    "custom-property-no-missing-var-function": true,
    "no-invalid-position-at-import-rule": true,
    "no-invalid-double-slash-comments": true,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "function-calc-no-unspaced-operator": true,
    "selector-type-no-unknown": [true, { ignore: ["custom-elements"] }],
    "unit-no-unknown": true,
    "keyframe-declaration-no-important": true,
    "no-duplicate-selectors": true,
    "plugin/file-max-lines": [1000, { "ignore": "blankLines" }],

    /* @stylistic */
    "@stylistic/color-hex-case": "lower",
    "@stylistic/function-comma-space-after": "always",
    "@stylistic/function-comma-space-before": "never",
    "@stylistic/function-max-empty-lines": 0,
    "@stylistic/function-whitespace-after": "always",
    "@stylistic/number-leading-zero": "always",
    "@stylistic/number-no-trailing-zeros": true,
    "@stylistic/string-quotes": "double",
    "@stylistic/unit-case": "lower",
    "@stylistic/value-list-max-empty-lines": 0,
    "@stylistic/property-case": "lower",
    "@stylistic/indentation": 2,
    "@stylistic/max-empty-lines": 1,
    "@stylistic/no-extra-semicolons": true,
  }
}
